name: 'Greeting1 Action'
description: 'Says hello to the provided name'
author: 'Sowmyashree M V'
inputs:
  name:
    description: 'Name to greet'
    required: false
    default: 'World'
outputs:
  greeting:
    description: 'The greeting message to Honeywell Team'
runs:
  using: 'node16'
  main: 'index.js'
